export const users = [
  {
    email: 'kimminjoo@gmail.com',
    password: '1',
    state: {
      name: '김민주',
      age: 24,
      sex: '남자',
      height: 172,
      weight: 68,
      disease: '고혈압/당뇨',
    },
    health: {
      title: '잘 관리되고 있음',
      weight: '68kg/+1',
      steps: '2115 step/-25',
      stress: '37/-5',
      desc: '연동된 헬스케어 장비로 부터 수집된 주간 평균 데이터로 4주 평균에 대해 증감치를 표시하고 있습니다.',
    },
    exercise: {
      title: '노력이 필요함',
      reps: '3회/-1',
      kalory: '1125kcal/-225',
      heartrate: '53-175bmp/66(평군)',
      desc: '주간 운동 현황으로 지난주 대비 증감치를 표시하고 있습니다. 운동중 심박의 경우 촤소-최대 심박과 평군을 보여줍니다.',
    },
    brain: {
      title: '뇌혈관질환 가능성 : 있음',
      cholesterol: '165mg/dl',
      triglycerides: '225mg/dl',
      hdlcholesterol: '189mg/dl',
      desc: '국민건강보험공단의 혈액 검시 데이터 100만건중 동일 연령대, 겅별 그룹주에서 뇌혈관질환 진료를 받은 대상자들의 검사결과들을 기반으로 학습한 예측 결과로 기계학습 정화도는 93% 입나다.',
    },
    dementia: {},
  },
  {
    email: 'seoyoon@gmail.com',
    password: '1',
    state: {
      name: '김서윤',
      age: 32,
      sex: '여자',
      height: 165,
      weight: 70,
      disease: '고혈압',
    },
    health: {
      title: '잘 관리되고 있음',
      weight: '70kg/-5',
      steps: '2000 step/-30',
      stress: '37/-5',
      desc: '연동된 헬스케어 장비로 부터 수집된 주간 평균 데이터로 4주 평균에 대해 증감치를 표시하고 있습니다.',
    },
    exercise: {
      title: '노력이 필요함',
      reps: '2회/-2',
      kalory: '1125kcal/-225',
      heartrate: '53-175bmp/66(평군)',
      desc: '주간 운동 현황으로 지난주 대비 증감치를 표시하고 있습니다. 운동중 심박의 경우 촤소-최대 심박과 평군을 보여줍니다.',
    },
    brain: {
      title: '뇌혈관질환 가능성 : 있음',
      cholesterol: '165mg/dl',
      triglycerides: '225mg/dl',
      hdlcholesterol: '189mg/dl',
      desc: '국민건강보험공단의 혈액 검시 데이터 100만건중 동일 연령대, 겅별 그룹주에서 뇌혈관질환 진료를 받은 대상자들의 검사결과들을 기반으로 학습한 예측 결과로 기계학습 정화도는 93% 입나다.',
    },
  },
];
